### PR TITLE
Calculate show reponse for unsupported template layout

### LINKED ISSUE #294: Show request succeeds even though the template is unsupported
If a `SetDisplayLayout ` request is sent to update the template to an unsupported template, the request is unsuccessful. 

```
SetDisplayLayout (request), id: 7
{
    displayLayout = "GRAPHIC_WITH_TEXT_AND_SOFTBUTTONS";
}

SetDisplayLayout (response), id: 7
{
    info = "The requested layout is not supported on this HMI";
    resultCode = "UNSUPPORTED_REQUEST";
    success = 0;
}
```

If a `Show` request is sent to show the same template, the request is successful. This means the developer does not know that the template update request failed.

```
Show (request), id: 9
{
    alignment = "LEFT_ALIGNED";
    mainField1 = "SmartDeviceLink (SDL)";
    mainField2 = "Swift Example App";
    mainField3 = "Odometer: Unsubscribed";
    mainField4 = "";
    mediaTrack = "";
    metadataTags = "{\n    mainField1 =     (\n    );\n    mainField2 =     (\n    );\n    mainField3 =     (\n    );\n}";
    templateConfiguration = "{\n    template = \"GRAPHIC_WITH_TEXT_AND_SOFTBUTTONS\";\n}";
    templateTitle = Home;
}

Show (response), id: 9
{
    resultCode = SUCCESS;
    success = 1;
}
```

### Reproduce
1. Send a `Show` request with the `templateConfiguration`'s `template` set to `GRAPHIC_WITH_TEXT_AND_SOFTBUTTONS` and check the response.

#### Expected Result
The `Show` request should fail because the generic_hmi currently does not support the `GRAPHIC_WITH_TEXT_AND_SOFTBUTTONS` template.

#### Actual Result
The `Show` request succeeds.

### PR DESCRIPTION
**Pull request by JackLivio**
In the event a template layout is not supported, the show response must calculate if the result should be a WARNINGS with info, or UNSUPPORTED_REQUEST.

Fixes #294 

Things to test

show strings only -> success
valid template only -> success
invalid template only -> unsupported failure
invalid template with show strings -> warnings success

### CODE REVIEW

File: src/js/Controllers/RpcFactory.js [hunk 1]
```diff
@@ -148,6 +148,65 @@ class RpcFactory {
             }
         })
     }
+    static UIShowResponse(rpc) {
+        var supportedTemplates = capabilities["MEDIA"].displayCapabilities.templatesAvailable;
+        const templateConfiguration = rpc.params.templateConfiguration;
+        const templateExists = templateConfiguration 
+            && templateConfiguration.template ? true : false;
```
Comment (iCollin) [inline src/js/Controllers/RpcFactory.js:155]:
```suggestion
        const templateExists = templateConfiguration && templateConfiguration.template;
```
seems this is a boolean already

File: src/js/Controllers/RpcFactory.js [hunk 2]
```diff
@@ -148,6 +148,65 @@ class RpcFactory {
...
+        // Calculated bool value if request only tried to set an unsupported template
+        const unsupportedRequest = templateExists 
+            && onlyChangeTemplate 
+            && !supportedTemplates.includes(templateConfiguration.template);
+        // Calculated bool value if request sets unsupported template value, but other show information was present.
+        const partialSuccess = !unsupportedRequest 
+            && templateExists 
+            && !onlyChangeTemplate 
+            && !supportedTemplates.includes(templateConfiguration.template);
+
```
Comment (iCollin) [inline src/js/Controllers/RpcFactory.js:171]: i think the logic here is a bit confusing, and I think we should simplify it, or at least short circuit the success case.

I think it could boil down to this, but I might be misunderstanding:
```
if (!templateConfiguration.template || supportedTemplates.includes(templateConfiguration.template))
    return "SUCCESS"

if (params.length == 3 && !showStrings.length)
    return "ERROR"

return "WARNINGS"
```

File: src/js/Controllers/RpcFactory.js [hunk 3]
```diff
@@ -183,29 +183,17 @@ class RpcFactory {
...
-                    "data": {
-                        "method": rpc.method
-                    },                    
-                    "code": 21, // Warnings
-                    "message" : "Unsupported Template. Remaining data in request was processed."
-                }
-            })
-        }
-
         return ({
```
Comment (iCollin) [inline src/js/Controllers/RpcFactory.js:186]: should this WARNINGS message really be a success response?

**Review by iCollin — APPROVED** [review]
