### PR TITLE
Fix/Pause position over timer bounds

### LINKED ISSUE #437: UI.SetMediaClockTimer(PAUSE) setting position time over bounds
### Bug Report
At the moment, sending `UI.SetMediaClockTimer(PAUSE)` to the HMI can set the position time over bounds

##### Reproduction Steps
1. Start core and HMI
2. Register and activate MEDIA application
3. Send `SetMediaClockTimer` request with params
```
{
	"updateMode": "COUNTUP",
	"startTime": {
		"hours": 0,
		"minutes": 0,
		"seconds": 0
	},
	"endTime": {
		"hours": 0,
		"minutes": 0,
		"seconds": 10
	}
}
```
4.  Wait for approximately 20 seconds
5. Send `SetMediaClockTimer` request with `{"updateMode":"PAUSE"}`

##### Expected Behavior
Media clock timer position remains at "00:00:10"

##### Observed Behavior
Media clock timer position is greater than "00:00:10"
Screenshot from 2021-09-03 09-35-25

##### Browser & Version Information
* Browser and Version: Chromium (Version 92.0.4515.159)
* Generic HMI Version: release/0.11.0
* Testing Against: RPC Builder

### PR DESCRIPTION
**Pull request by ShobhitAd**
Fixes #437 

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Core Tests
- COUNTUP case
  1. Send `SetMediaClockTimer` request with params
  ```
  {
	  "updateMode": "COUNTUP",
	  "startTime": {
		  "hours": 0,
		  "minutes": 0,
		  "seconds": 0
	  },
	  "endTime": {
		  "hours": 0,
		  "minutes": 0,
		  "seconds": 10
	  }
  }
  ```
  2.  Wait for approximately 20 seconds
  3. Send `SetMediaClockTimer` request with `{"updateMode":"PAUSE"}`

- COUNTDOWN case
  1. Send `SetMediaClockTimer` request with params
  ```
  {
	  "updateMode": "COUNTDOWN",
	  "startTime": {
		  "hours": 0,
		  "minutes": 0,
		  "seconds": 10
	  },
	  "endTime": {
		  "hours": 0,
		  "minutes": 0,
		  "seconds": 0
	  }
  }
  ```
  2.  Wait for approximately 20 seconds
  3. Send `SetMediaClockTimer` request with `{"updateMode":"PAUSE"}`

Core branch tested against: release/8.0.0 (https://github.com/smartdevicelink/sdl_core/commit/35f5a0684a36a2a965d5f0e9e784687fa7d82914)
Proxy+Test App name tested against: RPC Builder

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/js/MediaTrackInfo.js [hunk 1]
```diff
@@ -68,7 +68,15 @@ export default class MediaTrackInfo extends React.Component {
             }
 
             if (this.props.paused) {
-                position = startPosition
+                // Clamp position to timer bounds
+                console.log('[!] Paused', Object.assign({}, this))
+                if(startDate < endDate){ //COUNTUP
```
Comment (jacobkeeler) [inline src/js/MediaTrackInfo.js:73]: Might be slightly easier to take care of this in the previous `if` structure:

```
                startPosition = new Date(startDate.getTime() + offset)
                timeSince = new Date(startPosition.getTime() + ((now - this.props.updateTime) * this.props.countRate))
                // Start position is used if paused
                position = this.props.paused ? startPosition : timeSince
                // Clamp position to timer bounds
                position = endDate && position > endDate ? endDate : position
```

Then we could remove this section entirely

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/js/MediaTrackInfo.js (hunk 1 above)
Comment (jacobkeeler) [reply src/js/MediaTrackInfo.js:73]: `COUNTDOWN` version
```
                var startPosition = new Date(startDate.getTime() - offset)
                timeSince = new Date((now - this.props.updateTime) * this.props.countRate)
                var position = this.props.paused ? startPosition : new Date(startPosition - timeSince)
```

**Review by jacobkeeler — CHANGES_REQUESTED** [review]
Seems this works well enough for COUNTUP, but these changes need to also be applied to the `ProgressBar` component in order to work with COUNTDOWN.

Seems these changes will do the trick

```
        var timeSince = new Date((now - this.props.updateTime) * this.props.countRate)
        
        if (this.props.countDirection === "COUNTDOWN") {
            var startPosition = new Date(startDate.getTime() - offset)
            // Start position is used if paused
            var position = this.props.paused ? startPosition : new Date(startPosition - timeSince)
            // Clamp position to timer bounds
            position = position < endDate ? endDate : position
            var endPosition = startDate
        }
        else {
            startPosition = new Date(startDate.getTime() + offset)
            // Start position is used if paused
            position = this.props.paused ? startPosition : new Date(startPosition.getTime() + timeSince.getTime())
            // Clamp position to timer bounds
            position = position > endDate ? endDate : position
            endPosition = endDate
        }
```

File: src/js/MediaTrackInfo.js [hunk 2]
```diff
@@ -45,15 +45,17 @@ export default class MediaTrackInfo extends React.Component {
...
-
+                // Start position is used if paused
+                var position = this.props.paused ? startPosition : new Date(startPosition - timeSince)
                 // Clamp position to timer bounds
                 position = endDate && position < endDate ? endDate : position
                 var endTime = ""
             }
             else {
                 startPosition = new Date(startDate.getTime() + offset)
                 timeSince = new Date(startPosition.getTime() + ((now - this.props.updateTime) * this.props.countRate))
```
Comment (jacobkeeler) [inline src/js/MediaTrackInfo.js:56]:
```suggestion
                timeSince = new Date((now - this.props.updateTime) * this.props.countRate)
```
This change is needed as well

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: src/js/MediaTrackInfo.js (hunk 2 above)
Comment (jacobkeeler) [reply src/js/MediaTrackInfo.js:56]: In fact, with this change, `timeSince` and `startPosition` can be moved out of this `if` structure

File: src/js/MediaTrackInfo.js [hunk 3]
```diff
@@ -45,15 +45,17 @@ export default class MediaTrackInfo extends React.Component {
...
+                // Start position is used if paused
+                position = this.props.paused ? startPosition : new Date(startPosition + timeSince)
                 // Clamp position to timer bounds
                 position = endDate && timeSince > endDate ? endDate : timeSince
```
Comment (jacobkeeler) [inline src/js/MediaTrackInfo.js:60]:
```suggestion
                position = endDate && position > endDate ? endDate : position
```

File: src/js/MediaTrackInfo.js [hunk 4]
```diff
@@ -45,15 +45,17 @@ export default class MediaTrackInfo extends React.Component {
...
+                var position = this.props.paused ? startPosition : new Date(startPosition - timeSince)
                 // Clamp position to timer bounds
                 position = endDate && position < endDate ? endDate : position
                 var endTime = ""
             }
             else {
                 startPosition = new Date(startDate.getTime() + offset)
                 timeSince = new Date(startPosition.getTime() + ((now - this.props.updateTime) * this.props.countRate))
+                // Start position is used if paused
+                position = this.props.paused ? startPosition : new Date(startPosition + timeSince)
```
Comment (jacobkeeler) [inline src/js/MediaTrackInfo.js:58]:
```suggestion
                position = this.props.paused ? startPosition : new Date(startPosition.getTime() + timeSince.getTime())
```
Oddly, the `COUNTUP` case requires this `getTime()` call, or else things get a bit wonky. Don't know the exact reason

**Review by jacobkeeler — CHANGES_REQUESTED** [review]
Some other small changes to make this work properly

File: src/js/ProgressBar.js [hunk 5]
```diff
@@ -53,25 +53,25 @@ export default class ProgressBar extends React.Component {
...
                 break
         }
+        var timeSince = new Date((now - this.props.updateTime) * this.props.countRate)
 
         if (this.props.countDirection === "COUNTDOWN") {
             var startPosition = new Date(startDate.getTime() - offset)
-            var timeSince = new Date((now - this.props.updateTime) * this.props.countRate)
-            var position = new Date(startPosition  - timeSince)
+            // Start position is used if paused
+            var position = this.props.paused ? startPosition : new Date(startPosition - timeSince)
```
Comment (jacobkeeler) [inline src/js/ProgressBar.js:61]:
```suggestion
            var position = this.props.paused ? startPosition : new Date(startPosition.getTime() - timeSince.getTime())
```
For the sake of consistency, it doesn't make a difference here but we're using it in all other places for this PR

**Review by jacobkeeler — APPROVED** [review]
